spring:
  mvc:
    pathmatch:
      # SpringBoot2.4 版本之上需要配置策略，不然 swagger 会报错
      matching-strategy: ant-path-matcher
caffeine:
  # 最大缓存数（可以支持多少用户连接）
  maximumSize: 1000
  # 每次访问后数据源信息及连接过期时间（分钟）
  expireAfterAccess: 30
  # 数据源连接超时时间（秒）
  connectTimeout: 6